safe:        true

source:      .
destination: ./_site

future:      false
lsi:         false
highlighter: false
markdown:    kramdown
exclude:
  - scripts
  - templates
  - Makefile
  - requirements.txt
  - .gitignore

title: Journey to the Center of Hawkthorne
url: http://projecthawkthorne.com
author: Kyle Conroy
